# Generated by Django 4.2.1 on 2023-05-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_active_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('medical_practitioner', 'Medical Practitioner'), ('patient', 'Patient')], max_length=240),
        ),
    ]
