# Generated by Django 4.2.1 on 2023-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
